sudo: false
language: node_js
node_js:
- '5'
after_success: ./update-gh-pages.sh

env:
  global:
    secure: mf5dikdmjNWWok3bjbiE22HByiYUdcQnNbHojnWK++YbOs72G7Dg0D32761UNShpcHtqJNuOoSKQ58eMrxgtHbbBHT/iAZS2ssYP6//6brNPJuonWNCwSwmYLk1QLYViHgQOIjkBvYTzM6yVDSPlauye9i6FLTMFPTcpAIPcTDkwivUZCIQjnv/hdnyzGv7T4wkKV0ae8jKW0U9K77nCw2ATrPHcTZXZMgnzMWq8arkYCKoEXePG4ZJB/vdRPDW0LvQ9LI2AWy1VZV/hUjID3hQqREt/OQ8wb9frd0MEIgcIARuFOOL+TT/Py4fXr3mLFTOWlsJHXisSvjme6M0kfwSJHII0+rSK3aWiePtopVczMEtJIGQmVp0pA4IjXnrbw+oiln48KVbltC55TxO6aF0o0uBMFGiR+k0Wa0qpBMp0gpKRsCMjmxtubuuBUO7Q7zqxhhgMZnnnfhJ/I5n7tRTq/zlaztDPYAnnM6gvc56/90k59X9w7quNMiBlrZScgebJD/VD4/zjPbtxoSHX84M3cyoYcLjtFtmKOsWtarElHl2kUy830KBpagzgb/YaraZIYlKcjSwJD5adjSoCMSF/YNBqYmXbelCBXFKwrLIY3DJZjMKCHeoJzax3fOdwBLu6R7vG6c8Mvorv/yHAVAvxYTpbOOnwM2EF+j1TgcI=
